apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadcdnq4290-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadcdnq4290-tenant-component
    app.kubernetes.io/part-of: loadcdnq4290-tenant-app
  name: loadcdnq4290-tenant-component
  namespace: loadcdnq4290-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadcdnq4290-tenant-component
    weight: null
status: {}
